version: '2'
services:
  mastodon:
    image: lscr.io/linuxserver/mastodon
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - LOCAL_DOMAIN=${DOMAIN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=${DATABASE_HOST}
      - DB_USER=${DATABASE_USER}
      - DB_NAME=${DATABASE_NAME}
      - DB_PASS=${DATABASE_PASSWORD}
      - DB_PORT=${DATABASE_PORT}
      - WEB_DOMAIN=${DOMAIN}
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
    volumes:
      - ./mastodon:/config
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    volumes: 
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ""
    restart: unless-stopped

  letsencrypt:
    image: nginxproxy/acme-companion
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    restart: unless-stopped
    
volumes:
  certs:
